### PR TITLE
Windows XP Support

### PR DESCRIPTION
**Pull request by elishacloud**

### CODE REVIEW

**Comment by elishacloud** [comment]
There have been requests for Windows XP support on all my projects (including this one) and this is pretty easy since Visual Studio 2022 has a `v141_xp` toolkit.  I took this opportunity to clean-up some of the code and make it more consistent.  If there are specific change you are concerned about let me know.

**Comment by Trass3r** [comment]
I see (y)

**Comment by lorn10** [comment]
And for the sake of completeness it should be added that this could be perhaps also of some use for **Linux/Wine** users. :thinking: 

Wine may still support some Windows XP "code paths" better than those of the newer NT variants even if the main "target" is for quite some time Windows 7 (which will be raised in Wine 9.0 stable to Windows 10).

(The native Direct3D 9 API implementation in Mesa called [Gallium Nine](https://github.com/iXit/wine-nine-standalone) was build along the legacy XDDM/XPDM driver model not the newer WDDM one.)

**Comment by elishacloud** [comment]
Good point about Linux/Wine users.  The Windows XP version may work better for them.

As far as XDDM, XPDM and WDDM models, dxwrapper does not do much with any of these models.  Other than DDrawCompat, it only use WDDM for waiting for vsync calls.  But if WDDM is not available then it just uses a busy-wait loop.  So these models are not needed for dxwrapper.

**Comment by Squall-Leonhart** [comment]
> There have been requests for Windows XP support on all my projects (including this one) and this is pretty easy since Visual Studio 2022 has a `v141_xp` toolkit. I took this opportunity to clean-up some of the code and make it more consistent. If there are specific changes you are concerned about let me know.

There is no functional support for building XP apps with in VS v17, even with the xp toolkit installed.
16.4 was the last working version

**Pull request merged**
